// This file is a placeholder for your auto-generated Supabase types.
// It can be regenerated by running:
// npx supabase gen types typescript --project-id <your-project-id> > types/supabase-db.ts

export {};
