import { Video } from "@/types/videos";

export const videos: Video[] = [
  {
    id: "a1b2c3d4-1111-2222-3333-abcdeffedcba",
    title: "Counting to 10 for Kids",
    youtube_id: "KnSBNd3b0qI",
    subject: "Math",
    grade: 1,
    unit: "Unit 1: Numbers",
    duration: 185,
    thumbnail_url: "https://i.ytimg.com/vi/KnSBNd3b0qI/hqdefault.jpg",
  },
  {
    id: "a1b2c3d4-2222-3333-4444-abcdeffedcba",
    title: "Learning Basic Shapes",
    youtube_id: "OE_T1c0o99o",
    subject: "Math",
    grade: 1,
    unit: "Unit 2: Geometry",
    duration: 245,
    thumbnail_url: "https://i.ytimg.com/vi/OE_T1c0o99o/hqdefault.jpg",
  },
  {
    id: "a1b2c3d4-3333-4444-5555-abcdeffedcba",
    title: "Living and Non-Living Things",
    youtube_id: "p51FiPO2_kQ",
    subject: "Science",
    grade: 1,
    unit: "Unit 1: Life Science",
    duration: 312,
    thumbnail_url: "https://i.ytimg.com/vi/p51FiPO2_kQ/hqdefault.jpg",
  },
  {
    id: "b2c3d4e5-1111-2222-3333-bcdeffedcba1",
    title: "Addition and Subtraction for Grade 2",
    youtube_id: "igcoDFokKzU",
    subject: "Math",
    grade: 2,
    unit: "Unit 1: Basic Operations",
    duration: 450,
    thumbnail_url: "https://i.ytimg.com/vi/igcoDFokKzU/hqdefault.jpg",
  },
  {
    id: "b2c3d4e5-2222-3333-4444-bcdeffedcba1",
    title: "The Alphabet (Phonics)",
    youtube_id: "QXVzmzhxWWc?si=31sXJD1W6ZjAuC8C",
    subject: "English Language",
    grade: 7,
    unit: "Unit 1: Phonics and Reading",
    duration: 220,
    thumbnail_url: "https://i.ytimg.com/vi/QXVzmzhxWWc/hqdefault.jpg",
  },
];
